import { DarkTheme, DefaultTheme } from '@react-navigation/native';

export const lightmode = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        title: 'black',
        background: 'white',
        primary: 'black',
        text: 'black',
        interactiontext: 'black',
        username: 'black',
        postTime: '#666',
        Posttext: '#242526',
        icon: '#333',
        lock: 'black',
        tabBarActiveTintColor: 'black',
        tabBarInactiveTintColor: '#949494',
        textinput: '#ECECEC',
        about: '#242526',
        btncon: '#ECECEC',
        addbtnbg:'#2e64e515',
        addbtntext:'#2e64e5',
        chatright:'#8a3ab9',
        chatleft:'#ECECEC',
        camera:'#2e64e5',
        msgtext:'white',
        msgbg:'#3897f0',
        followingbtn:'white',
        followingbr:'#ECECEC',
        crossicon:'black',
        forminputtext:'#333333',
        forminputbg:'#fafafa',
        acbg:'#fafafa',
        acbc:'grey',
        div:'black'
    }
}

export const Darkmode = {
    ...DarkTheme,
    colors: {
        ...DarkTheme.colors,
        title: 'white',
        background: 'black',
        primary: 'white',
        text: 'white',
        postTime: 'white',
        interactiontext: 'white',
        username: 'white',
        Posttext: 'white',
        icon: 'white',
        lock: 'white',
        tabBarActiveTintColor: 'white',
        tabBarInactiveTintColor: '#949494',
        textinput: '#242526',
        about: '#949494',
        btncon: 'white',
        addbtnbg:'#fff',
        addbtntext:'#fff',
        chatright:'#3897f1',
        chatleft:'#242526',
        camera:'black',
        msgtext:'black',
        msgbg:'white',
        followingbtn:'black',
        followingbr:'white',
        crossicon:'white',
        forminputtext:'#fff',
        forminputbg:'#000',
        acbg:'#000',
        acbc:'#ECECEC',
        div:'#ECECEC'
    }
}